// <auto-generated />
namespace MHS_FINAL_PROJECT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class test_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "202104161450523_test_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
