// <auto-generated />
namespace MHS_FINAL_PROJECT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixsize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixsize));
        
        string IMigrationMetadata.Id
        {
            get { return "202104191525080_fix-size"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
